//! Contact events — agents occupying the same node at the same tick.

use dt_core::{AgentId, NodeId, Tick};

/// The type of spatial contact between two agents.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContactKind {
    /// Both agents are co-located at a road network node.
    Node,
    /// Both agents are in transit on the same edge (direction-agnostic).
    Edge,
}

/// A pairwise contact between two agents recorded during one tick.
///
/// Contacts are generated by dt-sim when two agents occupy the same node (or
/// are in transit on the same edge) during the spatial update phase.  The
/// simulation loop then calls [`BehaviorModel::on_contacts`][crate::BehaviorModel::on_contacts]
/// with all contacts for each woken agent.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContactEvent {
    /// The other agent in this contact (not the agent receiving the callback).
    pub other: AgentId,

    /// The node both agents occupy (or the edge midpoint anchor).
    pub location: NodeId,

    /// The tick at which the contact was observed.
    pub tick: Tick,

    /// Whether this is a node contact or an edge contact.
    pub kind: ContactKind,
}
